### ISSUE TITLE
How to get it working with Oculus Quest 2?

### ISSUE THREAD

**Issue by Manurocker95** [jorgejgnz/HPTK-Sample#1]
Edit:

It works, but only if you disable controllers and activate hand-tracking manually. Anyway, some weird behaviours happen...

Look at the video: https://youtu.be/V0zC8vuw1uw

-------------------------------------------------------------------------------------------------
Original:
-------------------------------------------------------------------------------------------------
Running the project doesn't work with OQ2 with controllers nor hand tracking, any clue?

Tested on Unity 2019.4.12 with latest oculus SDK

**Comment by jorgejgnz** [comment]
From the video I can identify two problems related with hand tracking:
1. Noisy hand tracking. It makes master hand to hop around. This can be related with light/contrast conditions.
2. Fast movements of slave hand when it tries to follow master hand on its hops.

If these are the problems that you are referring to, I can work on detecting noisy tracking and preventing those hops from occuring. There are several ways to deal with noisy hand tracking but they are not included in HPTK yet.

**Comment by jorgejgnz** [comment]
Oculus Integration has been updated to 20.1. This should fix your problems with controllers for Quest 2

**Comment by shinkaze33** [comment]
> From the video I can identify two problems related with hand tracking:
> 
>     1. Noisy hand tracking. It makes master hand to hop around. This can be related with light/contrast conditions.
> 
>     2. Fast movements of slave hand when it tries to follow master hand on its hops.
> 
> 
> If these are the problems that you are referring to, I can work on detecting noisy tracking and preventing those hops from occuring. There are several ways to deal with noisy hand tracking but they are not included in HPTK yet.

FWIW I had some success with a buffer caching high confidence frames over low confidence frames, however my solution was faulted as I cached positions rather than direction velocities causing 'popping' as well. ideally a buffer function should probably be treated like [client side prediction is treated in Multiplayer Authoritative movement](https://www.gabrielgambetta.com/client-side-prediction-server-reconciliation.html). 

 But replace "Client" and "Server" as a metaphor for  "Hand Dummy" and "Hand Track Input" respectively.

**Comment by jorgejgnz** [comment]
@shinkaze33 Thank you for your suggestion!

HPTK package now includes a new [hand physics configuration asset](https://github.com/jorgejgnz/HPTK/blob/master/Samples/Configurations/HandPhysics/DefaultClampedWeakWristConfiguration.asset) (used in [HPTK-Sample](https://github.com/jorgejgnz/HPTK-Sample)) for smoother physics. 
Following updates will include improvements and new options for Input module to deal with tracking noise and tracking loss.

**Comment by jorgejgnz** [comment]
@Manurocker95 HPTK has been updated to v0.3.0. This new version improves Input module by including new configuration assets to define tactics to deal with changes in tracking confidence and tracking loss.

HPTK-Sample now supports this new feature and the tracking feels much more solid.
Does this new update solves your problems with tracking in OQ2?

**Comment by jorgejgnz** [comment]
I will consider this issue as closed due to inactivity
