### ISSUE TITLE
Some References Missing in Scene

### ISSUE THREAD

**Issue by jknightdoeswork** [jorgejgnz/HPTK-Sample#3]
Opened in Unity 2019.4.4f1 and hit play, some values are missing in the scene and causes constant null references.

On the GameObjects LerpValues/Left and LerpValues/Right the ProxyHandLerpEvents script's OnErrorLerpUpdate event is missing it's ColorLerper.UpdateColor function.

![image](https://user-images.githubusercontent.com/1339925/105389996-2c5b9980-5bde-11eb-9012-fb4017aae938.png)
![image](https://user-images.githubusercontent.com/1339925/105390013-32ea1100-5bde-11eb-9326-e2560fae4c78.png)

Also, all of the ScaleLerper components are missing their Pivot reference.
![image](https://user-images.githubusercontent.com/1339925/105390317-852b3200-5bde-11eb-8157-d16113676958.png)

**Comment by jknightdoeswork** [comment]
Looks like this commit changed ColorLerper.UpdateColor to ColorLerper.UpdateAlpha and that broke the ProxyHandLerpEvents' references.

The ProxyHandLerpEvents should be updated to reference ColorLerper.UpdateAlpha

https://github.com/jorgejgnz/HPTK-Sample/commit/ff8106cd3deebc6fa92eed057487336e67d3f09f

**Comment by jknightdoeswork** [comment]
Note that the ScaleLerper's Pivot reference being null was fixed by having me Right Click -> Reimport on the LerpImport prefab. Looks like that was a Unity bug.

**Comment by jknightdoeswork** [comment]
Fixed the broken references to UpdateColor in https://github.com/jorgejgnz/HPTK-Sample/pull/4

Ignore the broken Pivot member as that was fixed by Reimport on the prefab (seems like a Unity bug).

**Comment by jorgejgnz** [comment]
@jknightdoeswork I didn't notice of that broken reference, thank you!
